### ISSUE TITLE
TSLint is failing

### ISSUE THREAD

**Issue by Simply007** [Kentico/custom-element-devkit#3]
### Brief bug description

Tn [this commit](https://github.com/Kentico/custom-element-devkit/commit/579ddcaae790517ef9cebc3310d12c66a55221b9) you declared two functions. They are used them before they were defined.

### Repro steps

run `npm run tslint`

### Expected behavior

Please fix the declaration order, or reconfigure tslint.

### Test environment

- https://travis-ci.org/Kentico/custom-element-devkit

### Error

```
$ npm run tslint
> custom-element-devkit@0.0.1 tslint /home/travis/build/Kentico/custom-element-devkit
> tslint --project tsconfig.json -e "./**/test/**" -e "./node_modules/**" "./**/*.ts?(x)"
ERROR: /home/travis/build/Kentico/custom-element-devkit/client/custom-elements/sheets/sheets.ts:22:7 - variable 'keepTheSameValue' used before declaration
ERROR: /home/travis/build/Kentico/custom-element-devkit/client/custom-elements/sheets/sheets.ts:25:7 - variable 'saveValue' used before declaration
```

**Comment by vilemj-Viclick** [comment]
Done.
